'use strict'
// Please don't delete the 'use strict' line above


/* Template Weapon Object

    {   // (RUNNING NUMBER)
        Name: "Temp",
        Type: "Rifle",
        Size: 0,
        Picture: "assets/Weapons/",
        Cost: 0,
        UnlockRank: 0,
        UnlockWeapon: undefined,
        Attachment: "Nothing"
        Ammo: [{Name: "Normal", Cost: 0}],
    },

*/


const weapons = [
    {   // 0
        Name: "Winfield M1873C",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_winfield_m1873_c_persp.png",
        Cost: 41,
        UnlockRank: 1,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "High Velocity", Cost: 90}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 1
        Name: "Winfield M1873C Silencer",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_winfield_m1873_c_silencer_persp.png",
        Cost: 55,
        UnlockRank: 1,
        UnlockWeapon: "Winfield M1873C",
        Attachment: "Silencer",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "High Velocity", Cost: 90}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },    
    {   // 2
        Name: "Winfield M1873C Marksman",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_winfield_m1873_c_marksman_persp.png",
        Cost: 56,
        UnlockWeapon: "Winfield M1873C Silencer",
        Attachment: "Marksman",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "High Velocity", Cost: 90}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 3
        Name: "Winfield M1873C Vandal",
        Type: "Rifle",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 35,
        UnlockWeapon: "Winfield M1873C Marksman",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "High Velocity", Cost: 90}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 4
        Name: "Winfield M1873C Vandal Striker",
        Type: "Rifle",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 39,
        UnlockRank: 1,
        UnlockWeapon: "Winfield M1873C Vandal",
        Attachment: "Melee Slash",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "High Velocity", Cost: 90}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 5
        Name: "Winfield M1873C Vandal Deadeye",
        Type: "Rifle",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 45,
        UnlockRank: 1,
        UnlockWeapon: "Winfield M1873C Vandal Striker",
        Attachment: "Deadeye",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "High Velocity", Cost: 90}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 6
        Name: "Springfield 1866",
        Type: "Single-shot Rifle",
        Size: 3,
        Picture: "assets/Weapons/",
        Cost: 38,
        UnlockRank: 1,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Dumdum", Cost: 90}, {Name: "Explosive", Cost: 90}],
    },
    {   // 7
        Name: "Springfield 1866 Marksman",
        Type: "Single-shot Rifle",
        Size: 3,
        Picture: "assets/Weapons/",
        Cost: 73,
        UnlockRank: 1,
        UnlockWeapon: "Springfield 1866",
        Attachment: "Marksman",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Dumdum", Cost: 90}, {Name: "Explosive", Cost: 90}],
    },
    {   // 8
        Name: "Springfield 1866 Compact",
        Type: "Single-shot Rifle",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 46,
        UnlockRank: 1,
        UnlockWeapon: "Springfield 1866 Marksman",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Dumdum", Cost: 90}, {Name: "Explosive", Cost: 90}],
    },
    {   // 9
        Name: "Springfield 1866 Compact Striker",
        Type: "Single-shot Rifle",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 56,
        UnlockRank: 1,
        UnlockWeapon: "Springfield 1866 Compact",
        Attachment: "Melee Slash",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Dumdum", Cost: 90}, {Name: "Explosive", Cost: 90}],
    },
    {   // 10
        Name: "Springfield 1866 Compact Deadeye",
        Type: "Single-shot Rifle",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 46,
        UnlockRank: 1,
        UnlockWeapon: "Springfield 1866 Compact Striker",
        Attachment: "Deadeye",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Dumdum", Cost: 90}, {Name: "Explosive", Cost: 90}],
    },
    {   // 11
        Name: "Romero 77",
        Type: "Single-shot Shotgun",
        Size: 3,
        Picture: "assets/Weapons/shotgun_2r_romero_persp.png",
        Cost: 34,
        UnlockRank: 1,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Dragon Breath", Cost: 50}, {Name: "Slug", Cost: 150}, {Name: "Penny Shot", Cost: 25}, {Name: "Starshell", Cost: 10}],
    },
    {   // 12
        Name: "Romero 77 Handcannon",
        Type: "Single-shot Shotgun",
        Size: 2,
        Picture: "assets/Weapons/shotgun_2r_romero_handcannon_persp.png",
        Cost: 26,
        UnlockRank: 1,
        UnlockWeapon: "Romero 77",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Dragon Breath", Cost: 50}, {Name: "Slug", Cost: 150}, {Name: "Penny Shot", Cost: 25}, {Name: "Starshell", Cost: 10}],
    },
    {   // 13
        Name: "Romero 77 Talon",
        Type: "Single-shot Shotgun",
        Size: 3,
        Picture: "assets/Weapons/shotgun_2r_romero_talon_persp.png",
        Cost: 59,
        UnlockRank: 1,
        UnlockWeapon: "Romero 77 Handcannon",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Dragon Breath", Cost: 50}, {Name: "Slug", Cost: 150}, {Name: "Penny Shot", Cost: 25}, {Name: "Starshell", Cost: 10}],
        Attachment: "Melee Slash",
    },
    {   // 14
        Name: "Romero 77 Hatchet",
        Type: "Single-shot Shotgun",
        Size: 2,
        Picture: "assets/Weapons/shotgun_2r_romero_hatchet_persp.png",
        Cost: 62,
        UnlockRank: 1,
        UnlockWeapon: "Romero 77 Talon",
        Attachment: "Melee Slash",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Dragon Breath", Cost: 50}, {Name: "Slug", Cost: 150}, {Name: "Penny Shot", Cost: 25}, {Name: "Starshell", Cost: 10}],
    },
    {   // 15
        Name: "Combat Axe",
        Type: "Melee Main",
        Size: 2,
        Picture: "assets/Weapons/melee_combat_axe_persp.png",
        Cost: 5,
        UnlockRank: 1,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}],
    },
    {   // 16
        Name: "Nagant M1895",
        Type: "Pistol",
        Size: 1,
        Picture: "assets/Weapons/",
        Cost: 24,
        UnlockRank: 1,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Poison", Cost: 35}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 17
        Name: "Nagant M1895 Precision",
        Type: "Pistol",
        Size: 2,
        Picture: "assets/Weapons/pistol_1r_nagant_m1895_precision_persp.png",
        Cost: 29,
        UnlockRank: 1,
        UnlockWeapon: "Nagant M1895",
        Attachment: "Stock",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Poison", Cost: 35}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 18
        Name: "Nagant M1895 Silencer",
        Type: "Pistol",
        Size: 1,
        Picture: "assets/Weapons/pistol_1r_nagant_m1895_silenced_persp.png",
        Cost: 53,
        UnlockRank: 1,
        UnlockWeapon: "Nagant M1895 Precision",
        Attachment: "Silencer",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Poison", Cost: 35}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 19
        Name: "Nagant M1895 Precision Deadeye",
        Type: "Pistol",
        Size: 2,
        Picture: "assets/Weapons/pistol_1r_nagant_m1895_deadeye_persp.png",
        Cost: 42,
        UnlockRank: 1,
        UnlockWeapon: "Nagant M1895 Silencer",
        Attachment: "Deadeye",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Poison", Cost: 35}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 20
        Name: "Nagant M1895 Pair",
        Type: "Dual Pistol",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 48,
        UnlockRank: 1,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Poison", Cost: 35}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 21
        Name: "Nagant M1895 Silencer Pair",
        Type: "Dual Pistol",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 106,
        UnlockRank: 1,
        UnlockWeapon: "Nagant M1895 Precision",
        Attachment: "Silencer",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Poison", Cost: 35}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 22
        Name: "Hand Crossbow",
        Type: "Crossbow",
        Size: 1,
        Picture: "assets/Weapons/special_hand_crossbow_standard_persp.png",
        Cost: 44,
        UnlockRank: 4,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Poison", Cost: 25}, {Name: "Chaos", Cost: 10}, {Name: "Choke", Cost: 20}],
    },
    {   // 23
        Name: "Crossbow",
        Type: "Crossbow",
        Size: 3,
        Picture: "assets/Weapons/Crossbow.png",
        Cost: 73,
        UnlockRank: 4,
        UnlockWeapon: "Hand Crossbow",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Shotbolt", Cost: 80}, {Name: "Explosive", Cost: 70}],
    },
    {   // 24
        Name: "Vetterli 71 Karabiner",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_vetterli_1871_persp.png",
        Cost: 105,
        UnlockRank: 6,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 60}, {Name: "Full Metal Jacket", Cost: 75}],
    },
    {   // 25
        Name: "Vetterli 71 Karabiner Deadeye",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_vetterli_1871_deadeye_persp.png",
        Cost: 130,
        UnlockRank: 6,
        UnlockWeapon: "Vetterli 71 Karabiner",
        Attachment: "Deadeye",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 60}, {Name: "Full Metal Jacket", Cost: 75}],
    },
    {   // 26
        Name: "Vetterli 71 Karabiner Bayonet",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_vetterli_1871_bayonet_persp.png",
        Cost: 155,
        UnlockRank: 6,
        UnlockWeapon: "Vetterli 71 Karabiner Deadeye",
        Attachment: "Melee Slash",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 60}, {Name: "Full Metal Jacket", Cost: 75}],
    },
    {   // 27
        Name: "Caldwell Pax",
        Type: "Pistol",
        Size: 1,
        Picture: "assets/Weapons/pistol_1r_caldwell_pax_persp",
        Cost: 100,
        UnlockRank: 10,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 60}, {Name: "Dumdum", Cost: 90}],
    },
    {   // 28
        Name: "Caldwell Pax Claw",
        Type: "Pistol",
        Size: 1,
        Picture: "assets/Weapons/pistol_1r_caldwell_pax_blade_persp.png",
        Cost: 125,
        UnlockRank: 10,
        UnlockWeapon: "Caldwell Pax",
        Attachment: "Melee Slash",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 60}, {Name: "Dumdum", Cost: 90}],
    },
    {   // 29
        Name: "Caldwell Pax Pair",
        Type: "Dual Pistol",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 200,
        UnlockRank: 10,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 60}, {Name: "Dumdum", Cost: 90}],
    },
    {   // 30
        Name: "Caldwell Pax Claw Pair",
        Type: "Dual Pistol",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 250,
        UnlockRank: 10,
        UnlockWeapon: "Caldwell Pax",
        Attachment: "Melee Slash",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 60}, {Name: "Dumdum", Cost: 90}],
    },
    {   // 31
        Name: "Machete",
        Type: "Melee Main",
        Size: 1,
        Picture: "assets/Weapons/melee_machete_persp.png",
        Cost: 18,
        UnlockRank: 12,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}],
    },
    {   // 32
        Name: "Martini Henry IC1",
        Type: "Single-shot Rifle",
        Size: 3,
        Picture: "assets/Weapons/",
        Cost: 122,
        UnlockRank: 16,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 70}, {Name: "Full Metal Jacket", Cost: 85}, {Name: "Explosive", Cost: 120}],
    },
    {   // 33
        Name: "Martini Henry IC1 Deadeye",
        Type: "Single-shot Rifle",
        Size: 3,
        Picture: "assets/Weapons/",
        Cost: 145,
        UnlockRank: 16,
        UnlockWeapon: "Martini Henry IC1",
        Attachment: "Deadeye",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 70}, {Name: "Full Metal Jacket", Cost: 85}, {Name: "Explosive", Cost: 120}],
    },
    {   // 34
        Name: "Martini Henry IC1 Marksman",
        Type: "Single-shot Rifle",
        Size: 3,
        Picture: "assets/Weapons/",
        Cost: 173,
        UnlockRank: 16,
        UnlockWeapon: "Martini Henry IC1 Deadeye",
        Attachment: "Marksman",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 70}, {Name: "Full Metal Jacket", Cost: 85}, {Name: "Explosive", Cost: 120}],
    },
    {   // 35
        Name: "Martini Henry IC1 Riposte",
        Type: "Single-shot Rifle",
        Size: 3,
        Picture: "assets/Weapons/",
        Cost: 164,
        UnlockRank: 16,
        UnlockWeapon: "Martini Henry IC1 Marksman",
        Attachment: "Melee Slash",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 70}, {Name: "Full Metal Jacket", Cost: 85}, {Name: "Explosive", Cost: 120}],
    },
    {   // 36
        Name: "Caldwell Rival 78",
        Type: "Shotgun",
        Size: 3,
        Picture: "assets/Weapons/shotgun_caldwell_rival_78_persp.png",
        Cost: 100,
        UnlockRank: 18,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Flechette", Cost: 45}, {Name: "Slug", Cost: 150}],
    },
    {   // 37
        Name: "Caldwell Rival 78 Handcannon",
        Type: "Shotgun",
        Size: 2,
        Picture: "assets/Weapons/shotgun_caldwell_rival_78_handcannon_persp.png",
        Cost: 85,
        UnlockRank: 18,
        UnlockWeapon: "Caldwell Rival 78",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Flechette", Cost: 45}, {Name: "Slug", Cost: 150}],
    },
    {   // 38
        Name: "Caldwell Conversion Pistol",
        Type: "Pistol",
        Size: 1,
        Picture: "assets/Weapons/pistol_1r_caldwell_conversion_persp.png",
        Cost: 25,
        UnlockRank: 22,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "Dumdum", Cost: 60}, {Name: "Full Metal Jacket", Cost: 75}],
    },
    {   // 39
        Name: "Caldwell Conversion Chain Pistol",
        Type: "Pistol",
        Size: 1,
        Picture: "pistol_1r_caldwell_conversion_chain_pistol_persp.png",
        Cost: 50,
        UnlockRank: 22,
        UnlockWeapon: "Caldwell Conversion Pistol",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "Dumdum", Cost: 60}, {Name: "Full Metal Jacket", Cost: 75}],
    },
    {   // 40
        Name: "Caldwell Conversion Uppercut",
        Type: "Pistol",
        Size: 1,
        Picture: "assets/Weapons/pistol_1r_caldwell_conversion_uppercut_persp.png",
        Cost: 275,
        UnlockRank: 22,
        UnlockWeapon: "Caldwell Conversion Chain Pistol",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}],
    },
    {   // 41
        Name: "Caldwell Conversion Pistol Pair",
        Type: "Dual Pistol",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 50,
        UnlockRank: 22,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "Dumdum", Cost: 60}, {Name: "Full Metal Jacket", Cost: 75}],
    },
    {   // 42
        Name: "Caldwell Conversion Chain Pistol Pair",
        Type: "Dual Pistol",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 100,
        UnlockRank: 22,
        UnlockWeapon: "Caldwell Conversion Pistol",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "Dumdum", Cost: 60}, {Name: "Full Metal Jacket", Cost: 75}],
    },
    {   // 43
        Name: "Caldwell Conversion Uppercut Pair",
        Type: "Dual Pistol",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 550,
        UnlockRank: 22,
        UnlockWeapon: "Caldwell Conversion Chain Pistol",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}],
    },
    {   // 44
        Name: "Sparks LLR",
        Type: "Single-shot Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_sparks_lrr_persp.png",
        Cost: 130,
        UnlockRank: 26,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 70}, {Name: "Poison", Cost: 35}],
    },
    {   // 45
        Name: "Sparks LLR Silencer",
        Type: "Single-shot Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_sparks_lrr_silenced_persp.png",
        Cost: 150,
        UnlockRank: 26,
        UnlockWeapon: "Sparks LLR",
        Attachment: "Silencer",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 70}, {Name: "Poison", Cost: 35}],
    },
    {   // 46
        Name: "Sparks LLR Sniper",
        Type: "Single-shot Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_sparks_lrr_sniper_persp.png",
        Cost: 199,
        UnlockRank: 26,
        UnlockWeapon: "Sparks LLR Silencer",
        Attachment: "Sniper",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 70}, {Name: "Poison", Cost: 35}],
    },
    {   // 47
        Name: "Bornheim No.3",
        Type: "Pistol",
        Size: 1,
        Picture: "assets/Weapons/pistol_1r_bornheim_no3_persp.png",
        Cost: 201,
        UnlockRank: 30,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 48
        Name: "Bornheim No.3 Extended",
        Type: "Pistol",
        Size: 1,
        Picture: "assets/Weapons/pistol_1r_bornheim_no3_extended_persp.png",
        Cost: 306,
        UnlockRank: 30,
        UnlockWeapon: "Bornheim No.3",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 49
        Name: "Bornheim No.3 Match",
        Type: "Pistol",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 224,
        UnlockRank: 30,
        UnlockWeapon: "Bornheim No.3 Extended",
        Attachment: "Stock",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 50
        Name: "Bornheim No.3 Pair",
        Type: "Dual Pistol",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 402,
        UnlockRank: 30,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 51
        Name: "Bornheim No.3 Extended Pair",
        Type: "Dual Pistol",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 612,
        UnlockRank: 30,
        UnlockWeapon: "Bornheim No.3",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 52
        Name: "Nagant M1895 Officer",
        Type: "Pistol",
        Size: 1,
        Picture: "assets/Weapons/pistol_1r_nagant_m1895_officer_persp.png",
        Cost: 66,
        UnlockRank: 36,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Poison", Cost: 35}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 53
        Name: "Nagant M1895 Officer Brawler",
        Type: "Pistol",
        Size: 1,
        Picture: "assets/Weapons/pistol_1r_nagant_m1895_officer_brawler_persp.png",
        Cost: 80,
        UnlockRank: 36,
        UnlockWeapon: "Nagant M1895 Officer",
        Attachment: "Melee Blunt",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Poison", Cost: 35}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 54
        Name: "Nagant M1895 Officer Pair",
        Type: "Pistol",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 132,
        UnlockRank: 36,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Poison", Cost: 35}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 55
        Name: "Nagant M1895 Officer Brawler Pair",
        Type: "Pistol",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 160,
        UnlockRank: 36,
        UnlockWeapon: "Nagant M1895 Officer",
        Attachment: "Melee Blunt",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Poison", Cost: 35}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 56
        Name: "Nagant M1895 Officer Carbine",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/pistol_1r_nagant_m1895_officer_carbine_persp.png",
        Cost: 155,
        UnlockRank: 36,
        UnlockWeapon: "Nagant M1895 Officer Brawler",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Poison", Cost: 35}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 57
        Name: "Nagant M1895 Officer Carbine Deadeye",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/",
        Cost: 211,
        UnlockRank: 36,
        UnlockWeapon: "Nagant M1895 Officer Carbine",
        Attachment: "Deadeye",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 58
        Name: "Winfield M1873",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/",
        Cost: 75,
        UnlockRank: 42,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 59
        Name: "Winfield M1873 Aperature",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_winfield_m1873_peephole_persp.png",
        Cost: 80,
        UnlockRank: 42,
        UnlockWeapon: "Winfield M18732",
        Attachment: "Aperature",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 60
        Name: "Winfield M1873 Talon",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_winfield_m1873_talon_persp.png",
        Cost: 100,
        UnlockRank: 42,
        UnlockWeapon: "Winfield M18732 Aperature",
        Attachment: "Melee Slash",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 61
        Name: "Winfield M1873 Swift",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_winfield_m1873_swift_persp.png",
        Cost: 128,
        UnlockRank: 42,
        UnlockWeapon: "Winfield M18732 Talon",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 62
        Name: "Winfield M1873 Musket Bayonet",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/",
        Cost: 137,
        UnlockRank: 42,
        UnlockWeapon: "Winfield M18732 Swift",
        Attachment: "Melee Slash",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "High Velocity", Cost: 90}],
    },
    {   // 63
        Name: "LeMat Mark II Revolver",
        Type: "Pistol-Shotgun Hybrid",
        Size: 1,
        Picture: "assets/Weapons/pistol_1r_lemat_persp.png",
        Cost: 95,
        UnlockRank: 46,
        UnlockWeapon: undefined,
        Attachment: "Shotgun",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "Full Metal Jacket", Cost: 75}],
        ShotgunAmmo: [{Name: "Normal", Cost: 0}, {Name: "Dragon Breath", Cost: 50}, {Name: "Slug", Cost: 150}, {Name: "Starshell", Cost: 10}]
    },
    {   // 64
        Name: "LeMat Mark II Revolver Pair",
        Type: "Pistol-Shotgun Hybrid",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 190,
        UnlockRank: 46,
        UnlockWeapon: undefined,
        Attachment: "Shotgun",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 50}, {Name: "Full Metal Jacket", Cost: 75}],
        ShotgunAmmo: [{Name: "Normal", Cost: 0}, {Name: "Dragon Breath", Cost: 50}, {Name: "Slug", Cost: 150}, {Name: "Starshell", Cost: 10}]
    },
    {   // 65
        Name: "Lebel 1886",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_lebel_persp.png",
        Cost: 397,
        UnlockRank: 52,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Spitzer", Cost: 220}],
    },
    {   // 66
        Name: "Lebel 1886 Talon",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_lebel_talon_persp.png",
        Cost: 422,
        UnlockRank: 52,
        UnlockWeapon: "Lebel 1886",
        Attachment: "Melee Slash",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Spitzer", Cost: 220}],
    },
    {   // 67
        Name: "Lebel 1886 Marksman",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_lebel_marksman_persp.png",
        Cost: 437,
        UnlockRank: 52,
        UnlockWeapon: "Lebel 1886 Talon",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Spitzer", Cost: 220}],
    },
    {   // 68
        Name: "Specter 1882",
        Type: "Shotgun",
        Size: 3,
        Picture: "assets/Weapons/shotgun_specter_1882_persp.png",
        Cost: 188,
        UnlockRank: 36,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Dragon Breath", Cost: 50}, {Name: "Flechette", Cost: 45}, {Name: "Slug", Cost: 150}],
    },
    {   // 69
        Name: "Specter 1882 Compact",
        Type: "Shotgun",
        Size: 2,
        Picture: "assets/Weapons/shotgun_specter_1882_compact_foregrip_persp.png",
        Cost: 164,
        UnlockRank: 36,
        UnlockWeapon: "Specter 1882",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Dragon Breath", Cost: 50}, {Name: "Flechette", Cost: 45}, {Name: "Slug", Cost: 150}],
    },
    {   // 70
        Name: "Specter 1882 Bayonet",
        Type: "Shotgun",
        Size: 3,
        Picture: "assets/Weapons/shotgun_specter_1882_bayonet_persp.png",
        Cost: 223,
        UnlockRank: 36,
        UnlockWeapon: "Specter 1882 Compact",
        Attachment: "Melee Slash",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Dragon Breath", Cost: 50}, {Name: "Flechette", Cost: 45}, {Name: "Slug", Cost: 150}],
    },
    {   // 71
        Name: "Winfield 1876 Centennial",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/",
        Cost: 338,
        UnlockRank: 58,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Full Metal Jacket", Cost: 75}, {Name: "Poison", Cost: 45}],
    },
    {   // 72
        Name: "Cavalry Saber",
        Type: "Melee Main",
        Size: 1,
        Picture: "assets/Weapons/melee_cavalrysaber.png",
        Cost: 60,
        UnlockRank: 62,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}],
    },
    {   // 73
        Name: "Winfield 1887 Terminus",
        Type: "Shotgun",
        Size: 3,
        Picture: "assets/Weapons/",
        Cost: 309,
        UnlockRank: 64,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Flechette", Cost: 45}, {Name: "Penny Shot", Cost: 25}],
    },
    {   // 74
        Name: "Winfield 1887 Terminus Handcannon",
        Type: "Shotgun",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 289,
        UnlockRank: 64,
        UnlockWeapon: "Winfield 1887 Terminus",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Flechette", Cost: 45}, {Name: "Penny Shot", Cost: 25}],
    },
    {   // 75
        Name: "Dolch 96",
        Type: "Pistol",
        Size: 1,
        Picture: "assets/Weapons/pistol_1r_dolch_96_persp.png",
        Cost: 750,
        UnlockRank: 68,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}],
    },
    {   // 76
        Name: "Dolch 96 Precision",
        Type: "Pistol",
        Size: 2,
        Picture: "assets/Weapons/pistol_1r_dolch_96_precision_persp",
        Cost: 790,
        UnlockRank: 68,
        UnlockWeapon: "Dolch 96",
        Attachment: "Stock",
        Ammo: [{Name: "Normal", Cost: 0}],
    },
    {   // 77
        Name: "Dolch 96 Pair",
        Type: "Pistol",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 1500,
        UnlockRank: 68,
        UnlockWeapon: "Dolch 96",
        Attachment: "Stock",
        Ammo: [{Name: "Normal", Cost: 0}],
    },
    {   // 78
        Name: "Mosin-Nagant M1891",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_mosin_nagant_m1891_persp.png",
        Cost: 490,
        UnlockRank: 72,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 70}, {Name: "Spitzer", Cost: 220}],
    },
    {   // 79
        Name: "Mosin-Nagant M1891 Bayonet",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_mosin_nagant_m1891_bayonet_persp.png",
        Cost: 540,
        UnlockRank: 72,
        UnlockWeapon: "Mosin-Nagant M1891 Obrez",
        Attachment: "Melee Slash",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 70}, {Name: "Spitzer", Cost: 220}],
    },
    {   // 80
        Name: "Mosin-Nagant M1891 Avtomat",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_mosin_nagant_avtomat_persp.png",
        Cost: 1250,
        UnlockRank: 72,
        UnlockWeapon: "Mosin-Nagant M1891 Bayonet",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 70}, {Name: "Spitzer", Cost: 220}],
    },
    {   // 81
        Name: "Mosin-Nagant M1891 Obrez",
        Type: "Rifle",
        Size: 2,
        Picture: "assets/Weapons/rifle_mosin_nagant_m1891_obrez_persp.png",
        Cost: 340,
        UnlockRank: 72,
        UnlockWeapon: "Mosin-Nagant M1891",
        Attachment: "Melee Slash",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 70}, {Name: "Spitzer", Cost: 220}],
    },
    {   // 82
        Name: "Mosin-Nagant M1891 Obrez Drum",
        Type: "Rifle",
        Size: 2,
        Picture: "assets/Weapons/",
        Cost: 350,
        UnlockRank: 72,
        UnlockWeapon: "Mosin-Nagant M1891 Sniper",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 70}, {Name: "Spitzer", Cost: 220}],
    },
    {   // 83
        Name: "Mosin-Nagant M1891 Obrez Mace",
        Type: "Rifle",
        Size: 2,
        Picture: "assets/Weapons/rifle_mosin_nagant_m1891_obrez_mace_persp.png",
        Cost: 310,
        UnlockRank: 72,
        UnlockWeapon: "Mosin-Nagant M1891 Sniper",
        Attachment: "Melee Blunt",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 70}, {Name: "Spitzer", Cost: 220}],
    },
    {   // 84
        Name: "Mosin-Nagant M1891 Sniper",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_mosin_nagant_m1891_sniper_persp.png",
        Cost: 550,
        UnlockRank: 72,
        UnlockWeapon: "Mosin-Nagant M1891 Drum",
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Incendiary", Cost: 70}, {Name: "Spitzer", Cost: 220}],
    },
    {   // 85
        Name: "Bomb Lance",
        Type: "Melee Main",
        Size: 3,
        Picture: "assets/Weapons/melee_bomblance_persp_01_persp.png",
        Cost: 199,
        UnlockRank: 78,
        UnlockWeapon: undefined,
        Attachment: "Boom",
        Ammo: [{Name: "Normal", Cost: 0}],
    },
    {   // 86
        Name: "Crown & King Auto-5",
        Type: "Shotgun",
        Size: 3,
        Picture: "assets/Weapons/shotgun_crown_and_king_pesp.png",
        Cost: 600,
        UnlockRank: 82,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Penny Shot", Cost: 25}],
    },
    {   // 87
        Name: "Nitro Express Rifle",
        Type: "Rifle",
        Size: 3,
        Picture: "assets/Weapons/rifle_nitro_express_persp.png",
        Cost: 1015,
        UnlockRank: 88,
        UnlockWeapon: undefined,
        Attachment: "Nothing",
        Ammo: [{Name: "Normal", Cost: 0}, {Name: "Dumdum", Cost: 150}, {Name: "Explosive", Cost: 200}],
    },
    
]

const melee = [
    {   // 0
        Name: "Dusters",
        Type: "Blunt",
        Size: 1,
        Picture: "assets/Weapons/tools_dusters.png",
        Cost: 15,
        UnlockRank: 20,
        UnlockWeapon: undefined,
    },
    {   // 1
        Name: "Knife",
        Type: "Slash",
        Size: 1,
        Picture: "assets/Weapons/Knife.png",
        Cost: 20,
        UnlockRank: 1,
        UnlockWeapon: undefined,
    },
    {   // 2
        Name: "Heavy Knife",
        Type: "Slash",
        Size: 1,
        Picture: "assets/Weapons/Heavy_Knife.png",
        Cost: 25,
        UnlockRank: 1,
        UnlockWeapon: "Knife",
    },
    {   // 3
        Name: "Knuckle Knife",
        Type: "Blunt",
        Size: 1,
        Picture: "assets/Weapons/Knuckle_Knife.png",
        Cost: 15,
        UnlockRank: 1,
        UnlockWeapon: "Dusters",
    }
]



const tools = [{}]
const consumable = [{}]
const traits = [{}]